<?php

add_filter('acf/settings/show_admin', '__return_false');

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_64f3d98e00baa',
	'title' => 'Menu Item Settings',
	'fields' => array(
		array(
			'key' => 'field_64f3debd27f55',
			'label' => 'Add sub-menu template',
			'name' => 'add_sub',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
			'ui' => 1,
		),
		array(
			'key' => 'field_64f61ccfa0288',
			'label' => 'Select Template',
			'name' => 'select_template',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64f3debd27f55',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'elementor_library',
			),
			'post_status' => '',
			'taxonomy' => array(
				0 => 'elementor_library_type:sub-menu-type',
			),
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'nav_menu_item',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_64c82f74d03ea',
	'title' => 'Project Page Header',
	'fields' => array(
		array(
			'key' => 'field_64ccf799e4538',
			'label' => 'Project Header Styles',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 1,
		),
		array(
			'key' => 'field_64c82f7420294',
			'label' => 'Project Header Style',
			'name' => 'project-header-style',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'no-image' => 'No Image',
				'half-image' => 'Half Image',
				'fullscreen-image' => 'Fullscreen Image',
				'boxed-image' => 'Boxed Image',
				'tall-image' => 'Tall Image',
				'creative' => 'Creative',
				'image-gallery-horizontal' => 'Image Gallery (Horizontal)',
				'image-gallery-vertical' => 'Image Gallery (Vertical)',
				'video' => 'Video',
				'custom-template' => 'Custom Template',
				'no-header' => 'No Header',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64cf88b7a2226',
			'label' => 'Custom Template',
			'name' => 'custom_template',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64c82f7420294',
						'operator' => '==',
						'value' => 'custom-tempalte',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'elementor_library',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_64cce83237034',
			'label' => 'Image Gallery',
			'name' => 'image_gallery',
			'aria-label' => '',
			'type' => 'photo_gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64c82f7420294',
						'operator' => '==',
						'value' => 'image-gallery-vertical',
					),
				),
				array(
					array(
						'field' => 'field_64c82f7420294',
						'operator' => '==',
						'value' => 'image-gallery-horizontal',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'fields[image_gallery' => array(
				'edit_modal' => 'Default',
				'images_limit' => '',
				'remove_edit_button' => 'No',
				'remove_delete_button' => 'No',
			),
			'edit_modal' => 'Default',
		),
		array(
			'key' => 'field_64ccf6722cc61',
			'label' => 'Video Provider',
			'name' => 'inner_video_provider',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64c82f7420294',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'self' => 'Self Hosted',
				'vimeo' => 'Vimeo',
				'youtube' => 'Youtube',
			),
			'default_value' => 'self',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64ccf6f507961',
			'label' => 'Video ID',
			'name' => 'embed_video_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64ccf6722cc61',
						'operator' => '==',
						'value' => 'vimeo',
					),
				),
				array(
					array(
						'field' => 'field_64ccf6722cc61',
						'operator' => '==',
						'value' => 'youtube',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64ccf6a507960',
			'label' => 'Self Video',
			'name' => 'self_video_upload',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64ccf6722cc61',
						'operator' => '==',
						'value' => 'self',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_64ccf7ca2daf3',
			'label' => 'Project Meta Entries',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 1,
		),
		array(
			'key' => 'field_64c8e9e86a5a7',
			'label' => 'Project Date',
			'name' => 'project_date',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Enter project date.',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64c8ea3767487',
			'label' => 'Project Client',
			'name' => 'project_client',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Enter project client.',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64c8ebd098297',
			'label' => 'Project Excerpt',
			'name' => 'project_excerpt',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => 'Enter project\'s summary here.',
			'new_lines' => '',
		),
		array(
			'key' => 'field_64c8ec38e0cd8',
			'label' => 'Project Button',
			'name' => 'project_button',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'Leave it empty if you don\'t want to display project button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_64c8ecc6e88a6',
			'label' => 'Custom Meta - 1',
			'name' => 'project_custom_meta_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64c8eca9e88a5',
			'label' => 'Custom Meta - 2',
			'name' => 'project_custom_meta_2',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => 'Enter project\'s summary here.',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_64c90129aaa1b',
	'title' => 'Header Settings',
	'fields' => array(
		array(
			'key' => 'field_64c902e941521',
			'label' => 'Header Layout',
			'name' => 'header_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64c901e0e56f6',
			'label' => 'Header Type',
			'name' => 'header_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'static' => 'Static',
				'dynamic' => 'Dynamic',
				'sticky' => 'Sticky',
				'fixed' => 'Fixed',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_64c8ef33c21bf',
	'title' => 'Project Settings',
	'fields' => array(
		array(
			'key' => 'field_64c8ef33f5ac7',
			'label' => 'Project Page Layout',
			'name' => 'project_page_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64ca2e5dbc26c',
			'label' => 'Project Header Layout',
			'name' => 'project_header_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6517357840ae3',
			'label' => 'Main Color (Dark)',
			'name' => 'main_light_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'For dark page layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ebebeb',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6517359340ae4',
			'label' => 'Main Background Color (Dark)',
			'name' => 'main_light_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'For dark page layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#191919',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64c8f16699ccc',
			'label' => 'Main Color (Light)',
			'name' => 'main_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'For light page layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#191919',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64c8f18999ccd',
			'label' => 'Main Background Color (Light)',
			'name' => 'main_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'For light page layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ebebeb',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64c8efec412ed',
			'label' => 'Featured Image Type',
			'name' => 'featured_image_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image' => 'Image',
				'video' => 'Video',
			),
			'default_value' => 'image',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64c8f0363678d',
			'label' => 'Video Provider',
			'name' => 'video_provider',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Select video provider here.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64c8efec412ed',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'self' => 'Self Hosted',
				'vimeo' => 'Vimeo',
				'youtube' => 'Youtube',
			),
			'default_value' => 'self',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64c8f0a4854ca',
			'label' => 'Video',
			'name' => 'self_video',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64c8f0363678d',
						'operator' => '==',
						'value' => 'self',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_64c8f105ffaef',
			'label' => 'Video ID',
			'name' => 'video_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64c8f0363678d',
						'operator' => '==',
						'value' => 'vimeo',
					),
				),
				array(
					array(
						'field' => 'field_64c8f0363678d',
						'operator' => '==',
						'value' => 'youtube',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Enter your video ID here',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_64e766c339ae8',
	'title' => 'Page Settings',
	'fields' => array(
		array(
			'key' => 'field_64e7675233f13',
			'label' => 'Color Settings',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64e79084c03b4',
			'label' => 'Page Layout',
			'name' => 'page_layout',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'Leave the color options empty if you want to use global color settings.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e766c3bab08',
			'label' => 'Main Color',
			'name' => 'main_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e7670ff056f',
			'label' => 'Main Background',
			'name' => 'main_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e7671ff0570',
			'label' => 'Secondary Background',
			'name' => 'secondary_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e76775d3a4c',
			'label' => 'Main Light color',
			'name' => 'main_light_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e7677ed3a4d',
			'label' => 'Main Light Background',
			'name' => 'main_light_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e76791d3a4e',
			'label' => 'Secondary Light Background',
			'name' => 'secondary_light_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e767d498c41',
			'label' => 'Header - Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64e768a371f94',
			'label' => 'Header Template',
			'name' => 'header_template',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Leave it empty if you want to use global header template.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'elementor_library',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => array(
				0 => 'elementor_library_type:header-type',
			),
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 1,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_64e7c9b8d234e',
			'label' => 'IMPORTANT NOTICE',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'If you using AJAX page transitions; \'<b>Header Template</b>\' selection will be visible only first load of this page. If you navigate this page from another; header will not change. And this selection will be applied all the pages you navigate from this page.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_64e7681498c42',
			'label' => 'Header Layout',
			'name' => 'header_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
				'blend' => 'Blend',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64e79afb1c069',
			'label' => 'Header Type',
			'name' => 'header_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'static' => 'Static',
				'dynamic' => 'Dynamic',
				'sticky' => 'Sticky',
				'fixed' => 'Fixed',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e79d60a6878',
			'label' => 'Sticky Header Color Set',
			'name' => 'sticky_header_color_set',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'sticky-dark' => 'Dark',
				'sticky-light' => 'Light',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e79d45a6877',
			'label' => 'Header Background Color',
			'name' => 'header_background_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Leave it empty for using global options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e79d82a6879',
			'label' => 'Sticky Header Background Color',
			'name' => 'sticky_header_background_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Leave it empty for using global options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e768e071f95',
			'label' => 'Footer Template',
			'name' => 'footer_template',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Leave it empty if you want to use global footer template. 
<br>
<br><b>IMPORTANT NOTICE: </b> If you using AJAX page transitions; this selection will be visible only first load of this page. If you navigate this page from another; footer will not change. And this selection will be applied all the pages you navigate from this page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'elementor_library',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => array(
				0 => 'elementor_library_type:footer-type',
			),
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 1,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_64e79039f96db',
			'label' => 'Footer Visibility',
			'name' => 'footer_visibility',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
			'ui' => 1,
		),
		array(
			'key' => 'field_64e7687398c43',
			'label' => 'Footer Layout',
			'name' => 'footer_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64e7696e705ea',
			'label' => 'Page Transitions',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64e76a2f705ec',
			'label' => 'Transition Type',
			'name' => 'transition_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'overlay' => 'Overlay',
				'block' => 'Blocks',
				'opacity' => 'Opacity',
				'columns' => 'Columns',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e76a6d3aebf',
			'label' => 'Transition Direction',
			'name' => 'transition_direction',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'up' => 'Up',
				'down' => 'Down',
				'left' => 'Left',
				'right' => 'Right',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64ea61fdce773',
			'label' => 'Overlay Color',
			'name' => 'trans_overlay_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64eb6dbb4ba05',
			'label' => 'Caption Color',
			'name' => 'trans_caption_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e76a8a3aec0',
			'label' => 'Transition Caption',
			'name' => 'transition_caption',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Leave it empty if you want to display global caption.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64e76a9b3aec1',
			'label' => 'Caption Position',
			'name' => 'caption_position',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'top-left' => 'Top - Left',
				'top-right' => 'Top - Right',
				'center' => 'Center',
				'bottom-left' => 'Bottom Left',
				'bottom-right' => 'Bottom Right',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64e76ae33aec2',
			'label' => 'Caption Animation Type',
			'name' => 'caption_animation_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'defaults' => 'Use Global',
				'default' => 'Chars',
				'opacity' => 'Opacity',
				'offset-x' => 'Offset-X',
			),
			'default_value' => 'defaults',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_64e76bb3a8414',
			'label' => 'Page Loader',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64e76bbea8415',
			'label' => 'Overlay Type',
			'name' => 'overlay_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'overlay' => 'Overlay',
				'blocks' => 'Blocks',
				'columns' => 'Columns',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e76c0fa8416',
			'label' => 'Progress Type',
			'name' => 'progress_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'percentage' => 'Percentage',
				'logo' => 'Logo',
				'caption' => 'Caption',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64ea604fd4e0e',
			'label' => 'Overlay Background',
			'name' => 'overlay_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64eb6dc84ba06',
			'label' => 'Caption Color',
			'name' => 'caption_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e76c62a8417',
			'label' => 'Caption Text',
			'name' => 'caption_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Leave it empty if you want to display global caption.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64e76c0fa8416',
						'operator' => '==',
						'value' => 'caption',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64e76c85a8418',
			'label' => 'Loader Logo',
			'name' => 'loader_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Leave it empty if you want to display global loader logo.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64e76c0fa8416',
						'operator' => '==',
						'value' => 'logo',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_64e7ab5d4f0af',
			'label' => 'Mouse Cursor',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64e7ab654f0b0',
			'label' => 'Cursor Style',
			'name' => 'cursor_style',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dot' => 'Dot',
				'circle' => 'Circle',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e7ab894f0b1',
			'label' => 'Cursor Layout',
			'name' => 'cursor_layout',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'dark' => 'Dark',
				'light' => 'Light',
				'blend' => 'Blend',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e7abb04f0b2',
			'label' => 'Cursor Color',
			'name' => 'cursor_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e7abc14f0b3',
			'label' => 'Cursor Text Color',
			'name' => 'cursor_text_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e7abce4f0b4',
			'label' => 'Cursor Icon Color',
			'name' => 'cursor_icon_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_64e7b1b55b76f',
			'label' => 'Smooth Scroll',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64e7b7ee5b770',
			'label' => 'Smooth Scroll',
			'name' => 'smooth_scroll',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'true' => 'Enable',
				'false' => 'Disable',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e7b8455b772',
			'label' => 'Normalize Scroll',
			'name' => 'normalize_scroll',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'true' => 'Enable',
				'false' => 'Disable',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e7b8675b774',
			'label' => 'Smooth Touch',
			'name' => 'smooth_touch',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Use Global',
				'true' => 'Enable',
				'false' => 'Disable',
			),
			'default_value' => 'default',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_64e7b8345b771',
			'label' => 'Smooth Strength',
			'name' => 'smooth_strength',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Leave it empty if you want to use global setting.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64e7b8585b773',
			'label' => 'Speed',
			'name' => 'speed',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Leave it empty if you want to use global setting.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64e7c29dcd900',
			'label' => 'Smooth Touch Strength',
			'name' => 'smooth_touch_strength',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Leave it empty if you want to use global setting.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 50,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

